# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shadows}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Menke"]
  s.date = %q{2010-04-15}
  s.description = %q{Require shadowed files in Ruby. Or how extending code can be made better!}
  s.email = %q{simon.menke@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/shadows.rb",
     "shadows.gemspec",
     "test/fixtures/a/four.rb",
     "test/fixtures/a/one.rb",
     "test/fixtures/b/four.rb",
     "test/fixtures/b/one.rb",
     "test/fixtures/b/three.rb",
     "test/fixtures/b/two.rb",
     "test/shadows_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/fd/shadows}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Require shadowed files in Ruby. Or how extending code can be made better.}
  s.test_files = [
    "test/fixtures/a/four.rb",
     "test/fixtures/a/one.rb",
     "test/fixtures/b/four.rb",
     "test/fixtures/b/one.rb",
     "test/fixtures/b/three.rb",
     "test/fixtures/b/two.rb",
     "test/shadows_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

